# Generated by Django 3.0.8 on 2020-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateTimeField(unique=True)),
                ('end', models.DateTimeField(unique=True)),
                ('comments', models.TextField()),
            ],
        ),
    ]
